### PR TITLE
submission

### PR DESCRIPTION
**Pull request by abenaTenkorang**
### This pull request is created to follow the correct gitflow
All implementations have been made in other branches and they are as follows;

- Created a navbar with a back-to-home icon, voice search bar, and settings nav links
- Created a home page with a list of countries
- Created a details page that contains the details of countries
- Added tested case to cover all the components rendering
- Added test case for the redux store as well as slice
- 

**Below is a video walkthrough of the project**

https://www.loom.com/share/e08a139914814f83b79bff647acaa122

**A video indicating path rectification**

https://www.loom.com/share/117188b3c095473ea707d20bccee6f37

### CODE REVIEW

**Review by julie-ify — CHANGES_REQUESTED** [review]
## Hi @abenaTenkorang,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [x] I am requesting these changes here because you have made changes to the required files in this PR. Kindly record a video presentation of the project and include the link in your readme file. Remember to show the piece of code you are proud of or find interesting.

- [x] The acknowledgment section in your readme file should contain an credits for Nelson Sakwa more specifically, instead of just Microverse.

- [x] When I ran your project I got this error page. There is mismatch between the actual file name and the import name. In the App.js file you should have this:

  ```
  import Details from './components/Details/details';
  ```

  jdidd

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by abenaTenkorang** [comment]
All changes have been rectified. I have added an additional video indicating that the path has been resolved. Thank you.

**Review by m05e5 — APPROVED** [review]
**Hi @abenaTenkorang 
You did great. Your project is complete!  There is nothing else to say other than... it's time to merge:shipit: 
Congratulations! 🎉 
CleverScornfulBuffalo-size_restricted

## Highlights


✔️ Clean Codebase
✔️ Nice UI
✔️ No linters error

## Optional suggestions

-[ optional ] Please change your `./components/Details/Details` to `./components/Details/details` in your App.js JS is case-sensitive when it comes to routing.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

**Comment by abenaTenkorang** [comment]
Thank you @m05e5  for the suggestion. I initially used details with small d but was getting routes error on my local server. I will try it again later

**Pull request merged**
